all:*
	ozc -c *.oz
test:
	ozengine launcher.ozf
test0:
	ozengine launcher.ozf --p 2 --s 7 --a 0
test1:
	ozengine launcher.ozf --p 2 --s 7 --a 1
test2:
	ozengine launcher.ozf --p 2 --s 7 --a 2
help:
	ozengine launcher.ozf --h
clean:
	rm *.ozf
