all:*
	python3 sokoban.py benchsGiven/sokoInst01 | ruby color.rb | ruby animate.rb 1
	python3 sokoban.py benchsGiven/sokoInst02 | ruby color.rb | ruby animate.rb 1
	python3 sokoban.py benchsGiven/sokoInst04 | ruby color.rb | ruby animate.rb 1
	python3 sokoban.py benchsGiven/sokoInst07 | ruby color.rb | ruby animate.rb 1
	python3 sokoban.py benchsGiven/sokoInst08 | ruby color.rb | ruby animate.rb 1
	python3 sokoban.py benchsGiven/sokoInst15 | ruby color.rb | ruby animate.rb 1