"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['network/Server.py']
DATA_FILES = ['images/archer.png',
 'images/attack_phase.png',
 'images/builder.png',
 'images/canon.png',
 'images/castle.png',
 'images/castle2.png',
 'images/castle3.png',
 'images/gold_mine.png',
 'images/miner.png',
 'images/moves_phase.png',
 'images/next_turn.png',
 'images/soldier.png',
 'images/turret.png',
 'images/upgrade.png',
 'images/wait_for_others.png',
 'images/wall.png']
OPTIONS = {'argv_emulation': True,
           'includes' : 'editor,graphics,main,network'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    #py_modules=['editor', 'graphics', 'main', 'network'],
    package=['editor', 'graphics', 'main', 'network']
)
